development:
  adapter: postgresql
  encoding: unicode
  database: throwback_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: throwback_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: throwback_production
  pool: 5
  username:
  password:
